export const widgetLabel = {
    grid: '栅格',
    form: '表单',
    table: '表格',
    tab: '标签页',
    div:'DIV',
    section: '区块',
    'sub-form': '子表单',
    card: '卡片',
    alert: '提示',
    'grid-col': '栅格列',
    'table-cell': '单元格',
    'tab-pane': '选项卡页',
    'data-table': '数据表格',
    input: '单行输入',
    textarea: '多行输入',
    number: '计数器',
    radio: '单选项',
    checkbox: '多选项',
    select: '下拉选项',
    time: '时间',
    'time-range': '时间范围',
    date: '日期',
    'date-range': '日期范围',
    switch: '开关',
    rate: '评分',
    color: '颜色选择器',
    slider: '滑块',
    'static-text': '静态文字',
    'html-text': 'HTML',
    button: '按钮',
    divider: '分隔线',
    'picture-upload': '图片',
    'file-upload': '文件',
    'rich-editor': '富文本',
    cascader: '级联选择',
    slot: '插槽',
    custom: 'Custom Component',
};
